### ISSUE TITLE
fix: lassie leaves duplicate comments

### ISSUE THREAD

**Issue by lukashass** [geprog/lassie-bot-dog#25]
See for example !274 :wink:

**Comment by anbraten** [comment]
Could be some pagination / sorting problem while retrieving the comments list

**Comment by anbraten** [comment]
[Docs](https://docs.gitlab.com/ce/api/notes.html#list-all-merge-request-notes) Maybe sort list by `asc` & `created_at` as Lassie is normally one of the first ones who comment.
